### ISSUE TITLE
Plan for QT binding?

### ISSUE THREAD

**Issue by liuyazui** [kovacsv/VisualScriptEngine#13]
Hi, node-editor programming is wonderful. I find that the VisualScriptEngine has binding for wxWidgets and web, do you have some plan to do the QT binding for VisualScriptEngine?

**Comment by kovacsv** [comment]
Currently I'm not planning to make the QT binding, but based on the wxWidgets port it couldn't be very hard to implement it.

**Comment by liuyazui** [comment]
Thank you.
