### ISSUE TITLE
Empty window (with WindowsEmbeddingDemo)

### ISSUE THREAD

**Issue by yvanblanchard** [kovacsv/VisualScriptEngine#16]
Hello,
I tried to launch the 'WindowsEmbeddingDemo' , but the windows is emtpy (using MSVS 2017 C++, on Win10 x64).
How can we use this demo example ?

![image](https://user-images.githubusercontent.com/63931618/171055647-c76e7200-09af-49a6-a6a7-8a35db43f488.png)

**Comment by kovacsv** [comment]
I would try right clicking on the canvas. 🙂
